apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-model-{{.ModelSlug}}
  labels:
    type: nfs
    storage-tier: models
    model-slug: {{.ModelSlug}}
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-models
  mountOptions:
    - nfsvers=4
    - hard
    - intr
  nfs:
    # NFS server is running on host (nova-nfs-server container)
    # The server is accessible from minikube nodes via the container name
    # With NFSv4 + fsid=0, /nfs-export is the root, so paths are relative to it
    server: nova-nfs-server
    path: /models/{{.ModelSlug}}
