apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-theme-pvc
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 50Mi
