apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-route
  namespace: kube-system
spec:
  hostnames:
  - hubble.lab.k8s.local
  
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: k8s-lab-https
    namespace: envoy-gateway-system
    sectionName: lab-https-termination
  
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    
    backendRefs:
    - name: hubble-ui
      port: 80