apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: k8s-lab-issuer
  namespace: cert-manager
spec:
  ca:
    # `ClusterIssuer` resource is not namespaced, so `secretName` is assumed to reference secret in `cert-manager` namespace.
    secretName: k8s-lab-ca