apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: envoy-redis
  namespace: envoy-gateway-system
spec:
  # Kubernetes configuration
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.2.11
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "25m"
        memory: "32Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
    # Password authentication from existing secret
    redisSecret:
      name: redis
      key: redis-password

  # Storage configuration
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
