apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
  # Create CA root secret in `cert-manager`
  namespace: cert-manager
spec:
  isCA: true
  commonName: selfsigned-ca
  secretName: ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io