apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-route
  namespace: kube-system
spec:
  hostnames:
    - hubble.{{.Domain}}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: nova-https
      namespace: envoy-gateway-system
      sectionName: lab-wildcard
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hubble-ui
          port: 80
