apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: hubble-oidc-auth
  namespace: kube-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: hubble-route

  oidc:
    provider:
      issuer: https://keycloak.auth.k8s.local/realms/k8s-lab
      authorizationEndpoint: https://keycloak.auth.k8s.local/realms/k8s-lab/protocol/openid-connect/auth
      tokenEndpoint: https://keycloak.auth.k8s.local/realms/k8s-lab/protocol/openid-connect/token

      backendRefs:
      - group: gateway.envoyproxy.io
        kind: Backend
        name: keycloak
        port: 443

    clientID: hubble
    clientSecret:
      name: hubble-oidc

    redirectURL: https://hubble.lab.k8s.local/oauth2/callback
    logoutPath: /oauth2/sign_out

    scopes:
    - openid
    - profile
    - email
    - groups
    
    forwardAccessToken: true
    refreshToken: true

  jwt:
    providers:
    - name: keycloak
      issuer: https://keycloak.auth.k8s.local/realms/k8s-lab
      remoteJWKS:
        uri: https://keycloak.auth.k8s.local/realms/k8s-lab/protocol/openid-connect/certs
        
        backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: keycloak      # ← réutilise ton Backend existant
          port: 443

  authorization:
    defaultAction: Deny
    rules:
    - name: allow-admins
      action: Allow
      principal:
        jwt:
          provider: keycloak
          claims:
          - name: groups
            valueType: StringArray
            values: ["ADMINS"]
