apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openwebui-route
  namespace: openwebui
spec:
  parentRefs:
  - name: nova-https
    namespace: envoy-gateway-system

  hostnames:
  - "chat.{{.Domain}}"
 
  rules:
  - matches:
    - path:
        type: PathPrefix 
        value: /
    backendRefs:
    - name: open-webui 
      port: 80