apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openwebui-route
  namespace: openwebui
spec:
  parentRefs:
  - name: k8s-lab-https
    namespace: envoy-gateway-system
    sectionName: lab-wildcard
 
  hostnames:
  - "open-webui.lab.k8s.local"
 
  rules:
  - matches:
    - path:
        type: PathPrefix 
        value: /
    backendRefs:
    - name: open-webui 
      port: 80