deployment:
  name: "envoy-control-plane"
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

service:
  type: "NodePort"

config:
  envoyGateway:
    extensionApis:
      enableBackend: true
    provider:
      kubernetes:
        rateLimitDeployment:
          container:
            env:
              - name: REDIS_AUTH
                valueFrom:
                  secretKeyRef:
                    name: redis
                    key: redis-password

    rateLimit:
      backend:
        type: Redis
        redis:
          url: envoy-redis.envoy-gateway-system.svc.cluster.local:6379
