apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-route
  namespace: kube-system
spec:
  parentRefs:
  - name: gateway-tls
    namespace: istio-gateway
    sectionName: https-termination
 
  hostnames:
  - "hubble.k8s-lab.local"
 
  rules:
  - matches:
    - path:
        type: PathPrefix 
        value: /
    backendRefs:
    - name: hubble-ui 
      port: 80