apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-credentials
  namespace: victoriametrics
type: Opaque
data:
  admin-GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: T0xBTnFPeUxtUTdkZU9EbGlheG00MkNIdHRCdTZqbmw=

