apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oauth2-proxy-tls
  namespace: oauth2-proxy
spec:
  secretName: oauth2-proxy-tls
  issuerRef:
    name: k8s-lab-issuer
    kind: ClusterIssuer
  commonName: oauth2-proxy.oauth2-proxy.svc.cluster.local
  dnsNames:
  - oauth2-proxy.oauth2-proxy.svc.cluster.local
  - proxy.auth.k8s.local