apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nova-https
  namespace: envoy-gateway-system
spec:
  gatewayClassName: eg-lab

  listeners:
  - name: nova-wildcard
    hostname: "*.{{.Domain}}"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - group: ""
        kind: Secret
        name: gateway-nova-tls

    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            service-type: nova
